modLoader="javafml"
loaderVersion="[43,)"
license="MPL-2.0"
[[mods]]
modId="warppads"
version="1.19.2-1.0"
displayName="Warp Pads"
logoFile="icon.png"
credits=""
authors="ThatPreston"
description='''
A mod that adds Steven Universe inspired warp pads!
'''
[[dependencies.warppads]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.warppads]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"